In [29]:
import pandas as pd
import numpy as np
# loading the libraries

In [30]:
df = pd.read_csv(r"C:\Users\Sujal\ML_Journey\04_linear_regression\Houseprice.csv")
df.head()
# reading the csv file and displaying its first 5 datas.

HouseAge  HouseFloor   HouseArea     HousePrice
0        52           2  112.945574  543917.179841
1        93           1  174.312126  817740.124828
2        15           4  125.219577  387992.503019
3        72           4  121.210124  240840.742388
4        61           4   59.221737  277273.386525

In [31]:
house_age = df["HouseAge"].to_numpy()
house_floor = df["HouseFloor"].to_numpy()
house_area = df["HouseArea"].to_numpy()
house_age = (house_age - np.mean(house_age)) / np.std(house_age)
house_floor = (house_floor - np.mean(house_floor)) / np.std(house_floor)
house_area = (house_area - np.mean(house_area)) / np.std(house_area)
house_price = df["HousePrice"].to_numpy()
print(house_age[:5])
print(house_floor[:5])
print(house_area[:5])
print(house_price[:5])

# converting the data into numpy array

[ 0.01571121  1.41605794 -1.24801633  0.69880717  0.32310439]
[-0.62767577 -1.31742937  0.75183142  0.75183142  0.75183142]
[-0.80743731  0.05759391 -0.6344213  -0.6909391  -1.56473577]
[543917.17984142 817740.12482771 387992.50301932 240840.74238818
 277273.38652523]


In [32]:
x0 = np.ones(len(house_age))
X2 = np.array([x0, house_age, house_floor, house_area]).T
print(X2[:5])
W = np.array([0, 0, 0, 0])
Y2 = np.array(house_price)
print(Y2[:5])
# defining parameters and converting them into proper frmat of matrix and also initial weights.

[[ 1.          0.01571121 -0.62767577 -0.80743731]
 [ 1.          1.41605794 -1.31742937  0.05759391]
 [ 1.         -1.24801633  0.75183142 -0.6344213 ]
 [ 1.          0.69880717  0.75183142 -0.6909391 ]
 [ 1.          0.32310439  0.75183142 -1.56473577]]
[543917.17984142 817740.12482771 387992.50301932 240840.74238818
 277273.38652523]


In [33]:
def cost_function(X, Y, W):
    """ Parameters:
    This function finds the Mean Square Error.
    Input parameters:
      X: Feature Matrix
      Y: Target Matrix
      W: Weight Matrix
    Output Parameters:
      J: accumulated mean square error.
    """
    m = len(Y)

    J = np.sum((X.dot(W) - Y) ** 2)/(2 * m)
    return J

In [34]:
inital_cost = cost_function(X2, Y2, W)
print(inital_cost)
# initial mean square error which should lower in more iterations

201528080199.132


In [35]:
def gradient_descent(X, Y, W, alpha, iterations):
    cost_history = [0] * iterations
    # creates list of 0s for number of iterations
    m = len(Y)

    for iteration in range(iterations):

        Y_pred = X.dot(W)

        loss = Y_pred - Y

        dw = (X.T.dot(loss) ) / (m)

        W = W - alpha * dw


        cost = cost_function(X, Y, W)
        # improves the cost in every iteration
        cost_history[iteration] = cost

        # does the calcualtion of gradient descent and then updates the cost_history every iteration

    return W, cost_history
# returns the final iterated weights and cost history of all iterations list

In [36]:
alpha = 0.001
new_weights, cost_history = gradient_descent(X2, Y2, W, alpha, 10000)

print(new_weights)
# Final weight after improvisations and updating of the previous values of W

print(cost_history[-1])
# the final and the most optimal cost in our iterated solution.

[579070.28694151  -8375.76493519 -34212.2969548  208591.59058666]
11235827038.293081


In [37]:
def rmse(Y, Y_pred):
  """
  This Function calculates the Root Mean Squres.
  Input Arguments:
    Y: Array of actual(Target) Dependent Varaibles.
    Y_pred: Array of predeicted Dependent Varaibles.
  Output Arguments:
    rmse: Root Mean Square.
  """
  rmse = np.sqrt(sum((Y-Y_pred)**2)/len(Y))
  return rmse

In [38]:
def r2(Y, Y_pred):
  """
   This Function calculates the R Squared Error.
  Input Arguments:
    Y: Array of actual(Target) Dependent Varaibles.
    Y_pred: Array of predeicted Dependent Varaibles.
  Output Arguments:
    rsquared: R Squared Error.
    """
  mean_y = np.mean(Y)
  ss_tot = sum((Y - mean_y) ** 2)
  ss_res = sum((Y - Y_pred) ** 2)
  r2 = 1 - (ss_res / ss_tot)
  return r2

In [39]:
Y_pred = X2.dot(new_weights)

print(rmse(Y2, Y_pred))
print(r2(Y2, Y_pred))

149905.48381092053
0.668087094331465
